// Captured from the real API (GET /api/knowledge-base and GET /api/assessments/1).
import type { Assessment, KnowledgeBase } from "../api/types";

export const knowledgeBase: KnowledgeBase = {
  ruleset_version: "2",
  risk_levels: ["Low", "Medium", "High"],
  indicators: [
    {
      key: "deforestation",
      label: "Deforestation",
      unit: "%",
      kind: "decimal",
      minimum: 0,
      maximum: 100,
      description: "Share of forest cover lost in the assessed area.",
    },
    {
      key: "turbidity",
      label: "Water turbidity",
      unit: "NTU",
      kind: "decimal",
      minimum: 0,
      maximum: 10000,
      description: "Cloudiness of nearby surface water.",
    },
    {
      key: "heavy_metals",
      label: "Heavy metal concentration",
      unit: "ppb",
      kind: "decimal",
      minimum: 0,
      maximum: 100000,
      description: "Combined heavy metals (e.g. mercury, lead, arsenic) measured in water.",
    },
    {
      key: "soil_erosion",
      label: "Soil erosion",
      unit: "%",
      kind: "decimal",
      minimum: 0,
      maximum: 100,
      description: "Share of the assessed land showing active erosion.",
    },
    {
      key: "reports",
      label: "Community reports",
      unit: "reports",
      kind: "integer",
      minimum: 0,
      maximum: 100000,
      description: "Reports of illegal mining activity received from the community.",
    },
    {
      key: "ph",
      label: "Water pH",
      unit: "pH",
      kind: "decimal",
      minimum: 0,
      maximum: 14,
      description: "Acidity of nearby surface water.",
    },
    {
      key: "dissolved_oxygen",
      label: "Dissolved oxygen",
      unit: "mg/L",
      kind: "decimal",
      minimum: 0,
      maximum: 50,
      description: "Oxygen available to aquatic life.",
    },
    {
      key: "biodiversity_loss",
      label: "Biodiversity loss",
      unit: "%",
      kind: "decimal",
      minimum: 0,
      maximum: 100,
      description: "Estimated decline in local species compared with baseline surveys.",
    },
    {
      key: "pm25",
      label: "PM2.5",
      unit: "\u00b5g/m\u00b3",
      kind: "decimal",
      minimum: 0,
      maximum: 2000,
      description: "Fine particulate matter in the air.",
    },
    {
      key: "noise_level",
      label: "Noise level",
      unit: "dB",
      kind: "decimal",
      minimum: 0,
      maximum: 200,
      description: "Typical noise level near the site.",
    },
    {
      key: "health_reports",
      label: "Health reports",
      unit: "reports",
      kind: "integer",
      minimum: 0,
      maximum: 100000,
      description: "Pollution-related health complaints recorded in the community.",
    },
  ],
  factors: [
    {
      id: "land_water",
      name: "Deforestation and pollution",
      description:
        "Combined evidence of land clearing and river pollution, weighted by how often the community reports mining activity.",
      indicators: ["deforestation", "turbidity", "heavy_metals", "soil_erosion", "reports"],
      rules: [
        {
          id: "R1.1",
          conclusion: "High",
          match: "all",
          note: "",
          conditions: [
            { indicator: "deforestation", operator: ">=", threshold: 70 },
            { indicator: "turbidity", operator: ">", threshold: 100 },
            { indicator: "heavy_metals", operator: ">", threshold: 50 },
            { indicator: "soil_erosion", operator: ">", threshold: 30 },
            { indicator: "reports", operator: ">", threshold: 5 },
          ],
        },
        {
          id: "R1.2",
          conclusion: "Medium",
          match: "all",
          note: "",
          conditions: [
            { indicator: "deforestation", operator: ">=", threshold: 70 },
            { indicator: "turbidity", operator: ">", threshold: 100 },
            { indicator: "heavy_metals", operator: ">", threshold: 50 },
            { indicator: "soil_erosion", operator: ">", threshold: 30 },
            { indicator: "reports", operator: "<=", threshold: 5 },
          ],
        },
        {
          id: "R1.3",
          conclusion: "Low",
          match: "all",
          note: "",
          conditions: [
            { indicator: "deforestation", operator: "<", threshold: 70 },
            { indicator: "turbidity", operator: "<=", threshold: 100 },
            { indicator: "heavy_metals", operator: "<=", threshold: 50 },
            { indicator: "soil_erosion", operator: "<=", threshold: 30 },
          ],
        },
        {
          id: "R1.4",
          conclusion: "Medium",
          match: "any",
          note: "Covers readings where some, but not all, land and water indicators are past their limits. The original rules gave no result here.",
          conditions: [
            { indicator: "deforestation", operator: ">=", threshold: 70 },
            { indicator: "turbidity", operator: ">", threshold: 100 },
            { indicator: "heavy_metals", operator: ">", threshold: 50 },
            { indicator: "soil_erosion", operator: ">", threshold: 30 },
          ],
        },
      ],
      recommendations: {
        Low: "No action needed beyond routine monitoring.",
        Medium: "Inspect the site and increase sampling of river turbidity and heavy metals.",
        High: "Refer the site to the regulator for enforcement, stop excavation and start planning water treatment and land reclamation.",
      },
    },
    {
      id: "water_chemistry",
      name: "pH and dissolved oxygen",
      description: "Acidic water and low oxygen both point to mining run-off.",
      indicators: ["ph", "dissolved_oxygen"],
      rules: [
        {
          id: "R2.1",
          conclusion: "High",
          match: "all",
          note: "",
          conditions: [
            { indicator: "ph", operator: "<", threshold: 6.5 },
            { indicator: "dissolved_oxygen", operator: "<", threshold: 4 },
          ],
        },
        {
          id: "R2.2",
          conclusion: "Medium",
          match: "any",
          note: "",
          conditions: [
            { indicator: "ph", operator: "<", threshold: 6.5 },
            { indicator: "dissolved_oxygen", operator: "<", threshold: 4 },
          ],
        },
        {
          id: "R2.3",
          conclusion: "Low",
          match: "all",
          note: "",
          conditions: [
            { indicator: "ph", operator: ">=", threshold: 6.5 },
            { indicator: "dissolved_oxygen", operator: ">=", threshold: 4 },
          ],
        },
      ],
      recommendations: {
        Low: "No action needed beyond routine monitoring.",
        Medium: "Retest water chemistry and check for upstream discharge points.",
        High: "Advise residents not to drink or fish from affected water and arrange an alternative water supply.",
      },
    },
    {
      id: "biodiversity",
      name: "Biodiversity loss",
      description: "Decline in local species compared with baseline surveys.",
      indicators: ["biodiversity_loss"],
      rules: [
        {
          id: "R3.1",
          conclusion: "High",
          match: "all",
          note: "",
          conditions: [{ indicator: "biodiversity_loss", operator: ">", threshold: 50 }],
        },
        {
          id: "R3.2",
          conclusion: "Medium",
          match: "all",
          note: "",
          conditions: [
            { indicator: "biodiversity_loss", operator: ">", threshold: 20 },
            { indicator: "biodiversity_loss", operator: "<=", threshold: 50 },
          ],
        },
        {
          id: "R3.3",
          conclusion: "Low",
          match: "all",
          note: "",
          conditions: [{ indicator: "biodiversity_loss", operator: "<=", threshold: 20 }],
        },
      ],
      recommendations: {
        Low: "No action needed beyond routine monitoring.",
        Medium: "Repeat species surveys to confirm the trend.",
        High: "Commission an ecological survey and plan habitat restoration.",
      },
    },
    {
      id: "air_quality",
      name: "Air quality",
      description: "Dust from excavation and processing, measured as PM2.5.",
      indicators: ["pm25"],
      rules: [
        {
          id: "R4.1",
          conclusion: "High",
          match: "all",
          note: "",
          conditions: [{ indicator: "pm25", operator: ">", threshold: 150 }],
        },
        {
          id: "R4.2",
          conclusion: "Medium",
          match: "all",
          note: "",
          conditions: [
            { indicator: "pm25", operator: ">", threshold: 50 },
            { indicator: "pm25", operator: "<=", threshold: 150 },
          ],
        },
        {
          id: "R4.3",
          conclusion: "Low",
          match: "all",
          note: "",
          conditions: [{ indicator: "pm25", operator: "<=", threshold: 50 }],
        },
      ],
      recommendations: {
        Low: "No action needed beyond routine monitoring.",
        Medium: "Monitor air quality near homes and schools.",
        High: "Issue an air quality advisory and require dust suppression on site.",
      },
    },
    {
      id: "noise",
      name: "Noise pollution",
      description: "Noise from machinery and dredging.",
      indicators: ["noise_level"],
      rules: [
        {
          id: "R5.1",
          conclusion: "High",
          match: "all",
          note: "",
          conditions: [{ indicator: "noise_level", operator: ">", threshold: 85 }],
        },
        {
          id: "R5.2",
          conclusion: "Medium",
          match: "all",
          note: "",
          conditions: [
            { indicator: "noise_level", operator: ">", threshold: 60 },
            { indicator: "noise_level", operator: "<=", threshold: 85 },
          ],
        },
        {
          id: "R5.3",
          conclusion: "Low",
          match: "all",
          note: "",
          conditions: [{ indicator: "noise_level", operator: "<=", threshold: 60 }],
        },
      ],
      recommendations: {
        Low: "No action needed beyond routine monitoring.",
        Medium: "Log noise complaints and measure levels at night.",
        High: "Restrict operating hours and require noise barriers.",
      },
    },
    {
      id: "community_health",
      name: "Community health",
      description: "Pollution-related health complaints in the community.",
      indicators: ["health_reports"],
      rules: [
        {
          id: "R6.1",
          conclusion: "High",
          match: "all",
          note: "",
          conditions: [{ indicator: "health_reports", operator: ">", threshold: 10 }],
        },
        {
          id: "R6.2",
          conclusion: "Medium",
          match: "all",
          note: "",
          conditions: [
            { indicator: "health_reports", operator: ">", threshold: 5 },
            { indicator: "health_reports", operator: "<=", threshold: 10 },
          ],
        },
        {
          id: "R6.3",
          conclusion: "Low",
          match: "all",
          note: "",
          conditions: [{ indicator: "health_reports", operator: "<=", threshold: 5 }],
        },
      ],
      recommendations: {
        Low: "No action needed beyond routine monitoring.",
        Medium: "Share the reports with the local health clinic for follow-up.",
        High: "Notify district health services and arrange community health screening.",
      },
    },
  ],
};

export const assessment: Assessment = {
  id: 1,
  community: "Tarkwa",
  notes: "",
  observations: {
    deforestation: 82.0,
    turbidity: 240.0,
    heavy_metals: 35.0,
    soil_erosion: 12.0,
    reports: 8,
    ph: 6.1,
    dissolved_oxygen: 5.2,
    biodiversity_loss: 33.0,
    pm25: 95.0,
    noise_level: 88.0,
    health_reports: 4,
  },
  evaluation: {
    overall_risk: "High",
    ruleset_version: "2",
    drivers: ["noise"],
    factors: [
      {
        id: "land_water",
        name: "Deforestation and pollution",
        level: "Medium",
        fired_rule: "R1.4",
        recommendation:
          "Inspect the site and increase sampling of river turbidity and heavy metals.",
        rules: [
          {
            id: "R1.1",
            conclusion: "High",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "deforestation",
                label: "Deforestation",
                unit: "%",
                operator: ">=",
                threshold: 70,
                observed: 82.0,
                satisfied: true,
              },
              {
                indicator: "turbidity",
                label: "Water turbidity",
                unit: "NTU",
                operator: ">",
                threshold: 100,
                observed: 240.0,
                satisfied: true,
              },
              {
                indicator: "heavy_metals",
                label: "Heavy metal concentration",
                unit: "ppb",
                operator: ">",
                threshold: 50,
                observed: 35.0,
                satisfied: false,
              },
              {
                indicator: "soil_erosion",
                label: "Soil erosion",
                unit: "%",
                operator: ">",
                threshold: 30,
                observed: 12.0,
                satisfied: false,
              },
              {
                indicator: "reports",
                label: "Community reports",
                unit: "reports",
                operator: ">",
                threshold: 5,
                observed: 8,
                satisfied: true,
              },
            ],
          },
          {
            id: "R1.2",
            conclusion: "Medium",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "deforestation",
                label: "Deforestation",
                unit: "%",
                operator: ">=",
                threshold: 70,
                observed: 82.0,
                satisfied: true,
              },
              {
                indicator: "turbidity",
                label: "Water turbidity",
                unit: "NTU",
                operator: ">",
                threshold: 100,
                observed: 240.0,
                satisfied: true,
              },
              {
                indicator: "heavy_metals",
                label: "Heavy metal concentration",
                unit: "ppb",
                operator: ">",
                threshold: 50,
                observed: 35.0,
                satisfied: false,
              },
              {
                indicator: "soil_erosion",
                label: "Soil erosion",
                unit: "%",
                operator: ">",
                threshold: 30,
                observed: 12.0,
                satisfied: false,
              },
              {
                indicator: "reports",
                label: "Community reports",
                unit: "reports",
                operator: "<=",
                threshold: 5,
                observed: 8,
                satisfied: false,
              },
            ],
          },
          {
            id: "R1.3",
            conclusion: "Low",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "deforestation",
                label: "Deforestation",
                unit: "%",
                operator: "<",
                threshold: 70,
                observed: 82.0,
                satisfied: false,
              },
              {
                indicator: "turbidity",
                label: "Water turbidity",
                unit: "NTU",
                operator: "<=",
                threshold: 100,
                observed: 240.0,
                satisfied: false,
              },
              {
                indicator: "heavy_metals",
                label: "Heavy metal concentration",
                unit: "ppb",
                operator: "<=",
                threshold: 50,
                observed: 35.0,
                satisfied: true,
              },
              {
                indicator: "soil_erosion",
                label: "Soil erosion",
                unit: "%",
                operator: "<=",
                threshold: 30,
                observed: 12.0,
                satisfied: true,
              },
            ],
          },
          {
            id: "R1.4",
            conclusion: "Medium",
            match: "any",
            fired: true,
            conditions: [
              {
                indicator: "deforestation",
                label: "Deforestation",
                unit: "%",
                operator: ">=",
                threshold: 70,
                observed: 82.0,
                satisfied: true,
              },
              {
                indicator: "turbidity",
                label: "Water turbidity",
                unit: "NTU",
                operator: ">",
                threshold: 100,
                observed: 240.0,
                satisfied: true,
              },
              {
                indicator: "heavy_metals",
                label: "Heavy metal concentration",
                unit: "ppb",
                operator: ">",
                threshold: 50,
                observed: 35.0,
                satisfied: false,
              },
              {
                indicator: "soil_erosion",
                label: "Soil erosion",
                unit: "%",
                operator: ">",
                threshold: 30,
                observed: 12.0,
                satisfied: false,
              },
            ],
          },
        ],
      },
      {
        id: "water_chemistry",
        name: "pH and dissolved oxygen",
        level: "Medium",
        fired_rule: "R2.2",
        recommendation: "Retest water chemistry and check for upstream discharge points.",
        rules: [
          {
            id: "R2.1",
            conclusion: "High",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "ph",
                label: "Water pH",
                unit: "pH",
                operator: "<",
                threshold: 6.5,
                observed: 6.1,
                satisfied: true,
              },
              {
                indicator: "dissolved_oxygen",
                label: "Dissolved oxygen",
                unit: "mg/L",
                operator: "<",
                threshold: 4,
                observed: 5.2,
                satisfied: false,
              },
            ],
          },
          {
            id: "R2.2",
            conclusion: "Medium",
            match: "any",
            fired: true,
            conditions: [
              {
                indicator: "ph",
                label: "Water pH",
                unit: "pH",
                operator: "<",
                threshold: 6.5,
                observed: 6.1,
                satisfied: true,
              },
              {
                indicator: "dissolved_oxygen",
                label: "Dissolved oxygen",
                unit: "mg/L",
                operator: "<",
                threshold: 4,
                observed: 5.2,
                satisfied: false,
              },
            ],
          },
        ],
      },
      {
        id: "biodiversity",
        name: "Biodiversity loss",
        level: "Medium",
        fired_rule: "R3.2",
        recommendation: "Repeat species surveys to confirm the trend.",
        rules: [
          {
            id: "R3.1",
            conclusion: "High",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "biodiversity_loss",
                label: "Biodiversity loss",
                unit: "%",
                operator: ">",
                threshold: 50,
                observed: 33.0,
                satisfied: false,
              },
            ],
          },
          {
            id: "R3.2",
            conclusion: "Medium",
            match: "all",
            fired: true,
            conditions: [
              {
                indicator: "biodiversity_loss",
                label: "Biodiversity loss",
                unit: "%",
                operator: ">",
                threshold: 20,
                observed: 33.0,
                satisfied: true,
              },
              {
                indicator: "biodiversity_loss",
                label: "Biodiversity loss",
                unit: "%",
                operator: "<=",
                threshold: 50,
                observed: 33.0,
                satisfied: true,
              },
            ],
          },
        ],
      },
      {
        id: "air_quality",
        name: "Air quality",
        level: "Medium",
        fired_rule: "R4.2",
        recommendation: "Monitor air quality near homes and schools.",
        rules: [
          {
            id: "R4.1",
            conclusion: "High",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "pm25",
                label: "PM2.5",
                unit: "\u00b5g/m\u00b3",
                operator: ">",
                threshold: 150,
                observed: 95.0,
                satisfied: false,
              },
            ],
          },
          {
            id: "R4.2",
            conclusion: "Medium",
            match: "all",
            fired: true,
            conditions: [
              {
                indicator: "pm25",
                label: "PM2.5",
                unit: "\u00b5g/m\u00b3",
                operator: ">",
                threshold: 50,
                observed: 95.0,
                satisfied: true,
              },
              {
                indicator: "pm25",
                label: "PM2.5",
                unit: "\u00b5g/m\u00b3",
                operator: "<=",
                threshold: 150,
                observed: 95.0,
                satisfied: true,
              },
            ],
          },
        ],
      },
      {
        id: "noise",
        name: "Noise pollution",
        level: "High",
        fired_rule: "R5.1",
        recommendation: "Restrict operating hours and require noise barriers.",
        rules: [
          {
            id: "R5.1",
            conclusion: "High",
            match: "all",
            fired: true,
            conditions: [
              {
                indicator: "noise_level",
                label: "Noise level",
                unit: "dB",
                operator: ">",
                threshold: 85,
                observed: 88.0,
                satisfied: true,
              },
            ],
          },
        ],
      },
      {
        id: "community_health",
        name: "Community health",
        level: "Low",
        fired_rule: "R6.3",
        recommendation: "No action needed beyond routine monitoring.",
        rules: [
          {
            id: "R6.1",
            conclusion: "High",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "health_reports",
                label: "Health reports",
                unit: "reports",
                operator: ">",
                threshold: 10,
                observed: 4,
                satisfied: false,
              },
            ],
          },
          {
            id: "R6.2",
            conclusion: "Medium",
            match: "all",
            fired: false,
            conditions: [
              {
                indicator: "health_reports",
                label: "Health reports",
                unit: "reports",
                operator: ">",
                threshold: 5,
                observed: 4,
                satisfied: false,
              },
              {
                indicator: "health_reports",
                label: "Health reports",
                unit: "reports",
                operator: "<=",
                threshold: 10,
                observed: 4,
                satisfied: true,
              },
            ],
          },
          {
            id: "R6.3",
            conclusion: "Low",
            match: "all",
            fired: true,
            conditions: [
              {
                indicator: "health_reports",
                label: "Health reports",
                unit: "reports",
                operator: "<=",
                threshold: 5,
                observed: 4,
                satisfied: true,
              },
            ],
          },
        ],
      },
    ],
  },
  overall_risk: "High",
  ruleset_version: "2",
  created_at: "2026-09-29T11:56:41+00:00",
};
